name: flojics_task
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  #ui
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.3
  flutter_screenutil: ^5.7.0
  animate_do: ^3.0.2
  flutter_rating_bar: ^4.0.1
  overlay_support: ^2.0.1
  fluttertoast: ^8.0.8
  expandable: ^5.0.1
  flutter_native_splash: ^2.1.5
  flutter_svg: ^2.0.2
  animations: ^2.0.7
  timeline_tile: ^2.0.0
  flutter_expanded_tile: ^0.3.7
  loader_overlay: ^2.2.0
  lottie: ^2.3.2
  velocity_x: ^3.3.0
  font_awesome_flutter: ^10.4.0
  shimmer_animation: ^2.1.0+1

  # Routing
  auto_route: ^5.0.2

  #utility
  path_provider: ^2.0.14
  image_picker: ^0.8.7
  file_picker: ^5.2.6
  fpdart: ^0.4.0
  flutter_local_notifications: ^13.0.0
  equatable: ^2.0.5
  url_launcher: ^6.1.10
  fancy_cart: ^0.0.6
  connectivity_plus: ^3.0.2

  #state management
  flutter_riverpod: 2.3.2
  event_bus: ^2.0.0

  # Local Storage
  shared_preferences: any
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Localization
  easy_localization: ^3.0.0

  # App Updates
  in_app_update: ^4.0.1
  upgrader: ^5.0.0
  in_app_review: any
  uuid: ^3.0.5

  # Debugging and Testing
  logging: ^1.0.2
  mockito: ^5.3.2
  lint: any

  # api
  dio: ^5.1.2
  json_annotation: ^4.5.0


dev_dependencies:
  hive_generator: ^2.0.0
  auto_route_generator: ^5.0.3
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.3.2

  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/
    - assets/translations/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
        - asset: assets/fonts/Tajawal-Light.ttf
        - asset: assets/fonts/Tajawal-Medium.ttf

flutter_native_splash:
  color: "ffffff"
  image: assets/images/logo.png


flutter_rename_app_plus:
  application_name: Shopify
  dart_package_name: flojics_task
  application_id: com.shopifyflojics.www
  bundle_id: com.shopifyflojics.www
  android_package_name: com.shopifyflojics.www

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true